# Ping
GET http://localhost/items/ping

###

# Create item
POST http://localhost/items/new
Authorization: Basic dm1 pass1
Content-Type: application/json

{
  "itemName": "artifact potion food 3",
  "itemBulkiness": 0.5,
  "itemDescription": "BLA.",
  "itemTypes": [
    "artifact",
    "potion",
    "food"
  ],
  "potionEffect": "anti evil",
  "potionDuration": "12 years",
  "artifactEffects": [
    "protects from evil",
    "makes horny"
  ],
  "foodTypes": ["a", "b"]
}

###

# Get item by id
GET http://localhost/items/id?id=6596922d52a028623f509773

###

# Delete item by id
DELETE http://localhost/items/delete?id=6596922d52a028623f509773
Authorization: Basic dm1 pass1

###

# Get all items with included and without excluded categories
GET http://localhost/items/category
Content-Type: application/json

{
  "include": ["potion", "artifact"],
  "exclude": ["fighting"]
}

###